name: Update database types

on:
  pull_requst:
    branches: -main

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - run: npm run update-types

      - name: check for file changes
        id: git_status
        run: |
          echo "::set-output name=status::$(git status -s)"

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
